// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.
// Regenerate: contractgen -package=hostsettings -provider-id=firewalla -go-package=settingscontract -emit=go -out <path>
package settingscontract

import (
	contract "github.com/ByteDeskAI/bytedesk-sdk-dependencies/v2/hostsettings"
	"github.com/ByteDeskAI/bytedesk-sdk-dependencies/v2/plugin"
)

var Validate = plugin.NewValidatedCommand[contract.ValidateRequest, contract.ValidateResult]("svc.firewalla.host.settings.section.v1.validate", 1, "efe0243152c02656f112508a497dc68106eb9f1fca2252d6a92ac91850b09105", "svc.firewalla.host.settings.section.v1.validate")
